<?php

namespace Tests\Feature;

use App\Mail\AtosMemoMail;
use App\Models\EmailQueue\EmailQueueRepository;
use App\Repositories\EmailQueue\DoctrineEmailQueueRepository;
//use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Mail;
use LaravelDoctrine\ORM\Facades\EntityManager;
use Tests\MailTracking;
use Tests\TestCase;

use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class EmailQueueTest extends TestCase
{
    use MailTracking;

    protected $email;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $em = new EntityManager();
        $this->email = new DoctrineEmailQueueRepository(
            app()->get('em'),
            app()->get('em')->getClassMetaData(\App\Models\EmailQueue\EmailQueue::class)
        );
        $this->setUpMailTracking();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testEmailSent()
    {
        if ($nextEmail = $this->email->testEmail())
        {
            Mail::fake();
            $testEmail = new AtosMemoMail($nextEmail);
            Mail::send($testEmail);
            Mail::assertSent(AtosMemoMail::class);
        }
    }
}
