<?php

namespace Tests\Feature;

use App\Models\Tagesmeldung\TagesmeldungRepository;
use Doctrine\DBAL\Schema\OracleSchemaManager;
use App\Overriders\OracleSchemaManagerOverride;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TagesmeldungTest extends TestCase
{
    protected $repository;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = $this->app->make(TagesmeldungRepository::class);
    }

    public function testTagesmeldungRepository()
    {
        $tableName = $this->app->get('em')->getClassMetadata('App\Models\Tagesmeldung\Tagesmeldung')->getTableName();

//     originalni   $schemaManager = $this->app->get('em')->getConnection()->getSchemaManager();
//      overriden da bi provjeravao i views
        $schemaManager = new OracleSchemaManagerOverride($this->app->get('em')->getConnection());

        $this->assertTrue($schemaManager->viewsExist(array(strtoupper($tableName))));
//        dd($schemaManager->listViews());
    }

}
